Задание 1

Для датафрейма log из материалов занятия создайте столбец source_type по следующим правилам:

     - если источник traffic_source равен yandex или google, то в source_type ставится organic
     
     - для источников paid и email из России - ставим ad
     
     - для источников paid и email не из России - ставим other
     
     - все остальные варианты берем из traffic_source без изменений

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('visit_log.csv', sep=';')
data

,timestamp,visit_id,url,region,user_id,traffic_source
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex
...,...,...,...,...,...,...
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email

In [3]:
data['source_type'] = data.traffic_source
data

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,yandex
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,yandex
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,yandex
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,yandex
...,...,...,...,...,...,...,...
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid,paid
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid,paid
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex,yandex
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid,paid
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email,email

In [4]:
data.loc[(data.traffic_source == 'yandex') | (data.traffic_source == 'google'), 'source_type'] = 'organic'
data

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic
...,...,...,...,...,...,...,...
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid,paid
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid,paid
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex,organic
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid,paid
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email,email

In [5]:
data.loc[((data.traffic_source == 'paid') | (data.traffic_source == 'email')) & (data.region == 'Russia'), 'source_type'] = 'ad'

In [8]:
data.sample(10)

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
1502,1549989639,0e2acfe1ad,https://host.ru/8fe7c39e5c598bbc54,Australia,7597ba2c08,google,organic
9815,1550039244,e5e7740a2e,https://host.ru/6fda01ec57f23abc9e,Belarus,1eccdf2721,paid,paid
6353,1550018927,ca055797db,https://host.ru/a5dda93e70318570c0,Russia,d949b1c3bc,yandex,organic
2959,1549998594,e78434d8ae,https://host.ru/ef57543002ce2a0f2a,Russia,227ebd0d3d,paid,ad
17493,1550085456,a05bb45b96,https://host.ru/5301a605bd574af1a5,Belarus,cede73dad0,google,organic
16284,1550078137,22a93dbe9b,https://host.ru/8fe7c39e5c598bbc54,Ukraine,2e69ecb4f1,direct,direct
3699,1550002867,c585c9ca31,https://host.ru/39fa884393666d45fc,Russia,1d8cef1cf8,direct,direct
18492,1550091720,4e528fac0f,https://host.ru/8880fd00cf23066541,Ukraine,78a17487eb,direct,direct
9261,1550035986,15ae6de6e2,https://host.ru/a8ce0b447c10a1deaa,Belarus,be3d3b9a9e,direct,direct
17054,1550082751,7190277243,https://host.ru/a5dda93e70318570c0,Russia,7da8706503,google,organic

In [9]:
data.loc[((data.traffic_source == 'paid') | (data.traffic_source == 'email')) & (data.region != 'Russia'), 'source_type'] = 'other'

In [10]:
data.sample(10)

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
15523,1550073559,212423d8f9,https://host.ru/1afc5618562365020a,Russia,414644bf61,direct,direct
13603,1550061793,e04441a6c4,https://host.ru/1afc5618562365020a,Belarus,1911cb696c,direct,direct
5353,1550012936,dfe1173a08,https://host.ru/3a80d6ca023aed7752,Ukraine,f61e050710,paid,other
7541,1550025858,0bdfed537a,https://host.ru/6407d4271d7b23cdf5,Ukraine,9f2a625dfe,google,organic
18508,1550091811,6c972498f5,https://host.ru/ee7c4e0674a284ee3f,Russia,eb388201cc,yandex,organic
4504,1550007795,0cf0476219,https://host.ru/05e41944dd85a900a6,Russia,7aac57cc25,paid,ad
16446,1550079104,8b10ca268e,https://host.ru/a8ce0b447c10a1deaa,Russia,05c14b6356,direct,direct
10829,1550045326,ddf62369eb,https://host.ru/ae8a036d7f44d0bcd9,Ukraine,ddf794dd86,direct,direct
3743,1550003204,62edb79cf6,https://host.ru/3004a8273caeef2867,Ukraine,95a6b45b17,google,organic
9240,1550035863,90cdd17fb5,https://host.ru/df646c3676cc259fa0,Russia,ee7ffcee95,paid,ad

In [11]:
# остальные остаются без изменения

Задание 2

В файле URLs.txt содержатся url страниц новостного сайта. Вам необходимо отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, затем 8 цифр, затем дефис. 

Выполните следующие действия:

- Прочитайте содержимое файла с датафрейм

- Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствии с заданным шаблоном

In [12]:
urls = pd.read_csv('URLs.txt')
urls

                                                  url
0                                             /world/
1                                            /latest/
2                                       /?updated=top
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
..                                                ...
88  /cis/35984145-kreml-prokommentiroval-soobschen...
89  /video/36071019-olimpiyskie-obekty-rio-prevrat...
90  /science/36151301-nazvano-posledstvie-zloupotr...
91  /incidents/36027330-vospitatelnitsu-zatravili-...
92  /world/36103095-dominikanskih-zhurnalistov-ubi...

[93 rows x 1 columns]

In [14]:
# импортируем модуль Re для регулярных выражений
import re

In [21]:
pattern = r'\d{8}'

In [22]:
urls[urls.url.str.contains(pattern)]

                                                  url
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
5   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6   /video/36001498-poyavilis-pervye-podrobnosti-g...
7   /world/36007585-tramp-pridumal-kak-reshit-ukra...
..                                                ...
88  /cis/35984145-kreml-prokommentiroval-soobschen...
89  /video/36071019-olimpiyskie-obekty-rio-prevrat...
90  /science/36151301-nazvano-posledstvie-zloupotr...
91  /incidents/36027330-vospitatelnitsu-zatravili-...
92  /world/36103095-dominikanskih-zhurnalistov-ubi...

[84 rows x 1 columns]

Задание 3

В датафрейме data создайте столбец lemmas, в котором вычислите леммы поисковых запросов из столбца keyword. Леммы должны иметь строковый тип.

In [23]:
data = pd.DataFrame({
    'keyword': ['курс гривны к рублю', 'доллары в рубли', '100 долларов в рублях', 'курс рубля'],
    'shows': [125076, 114173, 97534, 53546],
})

In [24]:
data

                 keyword   shows
0    курс гривны к рублю  125076
1        доллары в рубли  114173
2  100 долларов в рублях   97534
3             курс рубля   53546

In [25]:
pip install pymystem3

Collecting pymystem3
  Downloading pymystem3-0.2.0-py3-none-any.whl (10 kB)
Requirement already satisfied: requests in c:\users\user\anaconda3\lib\site-packages (from pymystem3) (2.22.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\user\anaconda3\lib\site-packages (from requests->pymystem3) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\user\anaconda3\lib\site-packages (from requests->pymystem3) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\lib\site-packages (from requests->pymystem3) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\user\anaconda3\lib\site-packages (from requests->pymystem3) (3.0.4)
Installing collected packages: pymystem3
Successfully installed pymystem3-0.2.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
data = pd.DataFrame({
    'keyword': ['курс гривны к рублю', 'доллары в рубли', '100 долларов в рублях', 'курс рубля'],
    'shows': [125076, 114173, 97534, 53546],
})

In [4]:
data

                 keyword   shows
0    курс гривны к рублю  125076
1        доллары в рубли  114173
2  100 долларов в рублях   97534
3             курс рубля   53546

In [5]:
from pymystem3 import Mystem

In [11]:
def find_lemmas(row):
    m = Mystem()
    return ' '.join(m.lemmatize(row ['keyword']))

In [12]:
data['lemmas'] = data.apply(find_lemmas, axis=1)
data

                 keyword   shows                        lemmas
0    курс гривны к рублю  125076  курс   гривна   к   рубль \n
1        доллары в рубли  114173         доллар   в   рубль \n
2  100 долларов в рублях   97534   100   доллар   в   рубль \n
3             курс рубля   53546               курс   рубль \n

In [18]:
%%time
data['lemmas'] = data.apply(find_lemmas, axis=1)
data

Wall time: 4.21 s

                 keyword   shows                        lemmas
0    курс гривны к рублю  125076  курс   гривна   к   рубль \n
1        доллары в рубли  114173         доллар   в   рубль \n
2  100 долларов в рублях   97534   100   доллар   в   рубль \n
3             курс рубля   53546               курс   рубль \n